/**
 * Type Definitions
 * 
 * Generated GraphQL types and custom frontend types.
 * GraphQL types will be generated by codegen in Task 1.3.
 */

// Re-export generated types when available
// export * from './schema';

// Custom frontend types
export interface FoundationConfig {
  graphqlEndpoint: string;
  wsEndpoint: string;
  enableDevTools: boolean;
}

export interface ErrorContext {
  operation: string;
  variables?: any;
  user?: any;
  requestId: string;
}