AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket and CloudFront Distribution for Learning Platform Content'

Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: learning-platform-content
  
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  # S3 Bucket for content storage
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      
      # Lifecycle configuration
      LifecycleConfiguration:
        Rules:
          - Id: TempUploadsCleanup
            Status: Enabled
            Prefix: temp/uploads/
            ExpirationInDays: 1
          
          - Id: IncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
          
          - Id: VideoProcessingTransition
            Status: Enabled
            Prefix: videos/
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
      
      # CORS configuration
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedOrigins: 
              - 'https://*.yourdomain.com'
              - 'http://localhost:3000'
              - 'http://localhost:3001'
            ExposedHeaders: [ETag, 'x-amz-meta-*']
            MaxAge: 3000
      
      # Server-side encryption
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      
      # Public access block
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      
      # Notification configuration for Lambda triggers
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/
            Function: !GetAtt VideoProcessingFunction.Arn

  # Bucket policy
  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${ContentBucket}/public/*'
          
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource: 
              - !Sub '${ContentBucket}'
              - !Sub '${ContentBucket}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  # Origin Access Control for CloudFront
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${BucketName}-${Environment}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  ContentDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub 'Learning Platform Content Distribution - ${Environment}'
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        
        # Origins
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt ContentBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        
        # Default cache behavior
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          
          # Cache policy
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingOptimized
          
          # Response headers policy
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
        
        # Additional cache behaviors
        CacheBehaviors:
          # API responses - no caching
          - PathPattern: '/api/*'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # Managed-CachingDisabled
        
        # Custom error pages
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: '/404.html'
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/404.html'

  # Security headers policy
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${BucketName}-${Environment}-security-headers'
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            Override: true
            FrameOption: DENY
          ReferrerPolicy:
            Override: true
            ReferrerPolicy: strict-origin-when-cross-origin
          StrictTransportSecurity:
            Override: true
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true

  # Lambda function for video processing trigger
  VideoProcessingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${BucketName}-${Environment}-video-processing'
      Runtime: nodejs18.x
      Handler: index.handler
      Role: !GetAtt VideoProcessingRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            console.log('Video processing triggered:', JSON.stringify(event, null, 2));
            // This would trigger MediaConvert job
            return { statusCode: 200, body: 'Processing initiated' };
          };

  # IAM role for Lambda function
  VideoProcessingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${ContentBucket}/*'
        - PolicyName: MediaConvertAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mediaconvert:*
                Resource: '*'

  # Lambda permission for S3 to invoke function
  VideoProcessingPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref VideoProcessingFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub '${ContentBucket}'

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref ContentBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN of the created S3 bucket
    Value: !GetAtt ContentBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref ContentDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  
  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt ContentDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomainName'
  
  OriginAccessControlId:
    Description: Origin Access Control ID
    Value: !GetAtt OriginAccessControl.Id
    Export:
      Name: !Sub '${AWS::StackName}-OriginAccessControlId'